# Generated by Django 3.1.6 on 2022-07-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='Product',
        ),
    ]
